namespace EBA.Graph.Bitcoin.Strategies;

public class T2TEdgeStrategy(EdgeKind kind, bool serializeCompressed) 
    : StrategyBase<T2TEdge, T2TEdgeStrategy>(
        $"edges_" +
        $"{kind.Source}_" +
        $"{kind.Relation}_" +
        $"{kind.Target}",
        serializeCompressed),
    IElementSchema<T2TEdge>
{
    public static EntityTypeMapper<T2TEdge> Mapper { get; } = new EntityTypeMapper<T2TEdge>(
        new MappingBuilder<T2TEdge>()
            .MapSourceId(TxNodeStrategy.IdSpace, e => e.Source.Txid)
            .MapTargetId(TxNodeStrategy.IdSpace, e => e.Target.Txid)
            .MapValue(e => e.Value)
            .MapBlockHeight(e => e.BlockHeight)
            .MapEdgeType(e => e.Relation)
            .ToArray());

    public static T2TEdge Deserialize(TxNode source, TxNode target, IRelationship relationship)
    {
        return new T2TEdge(
            source: source,
            target: target,
            timestamp: 0,
            blockHeight: Mapper.GetValue(x => x.BlockHeight, relationship.Properties),
            value: Mapper.GetValue(x => x.Value, relationship.Properties),
            type: Enum.Parse<RelationType>(relationship.Type));
    }

    public override string GetQuery(string csvFilename)
    {
        // The following is an example of the query generated by this method.
        // Indentation and line break is added for readability and is not 
        // included in the generated query.
        //
        //
        // LOAD CSV WITH HEADERS FROM 'file:///filename.csv' AS line
        // FIELDTERMINATOR '	'
        //
        // MATCH
        //     (source:Tx {Txid:line.SourceId}),
        //     (target:Tx {Txid:line.TargetId}),
        //     (block:Block {Height:toInteger(line.Height)})
        //
        // CREATE (source)-[:Redeems {Height:toInteger(line.Height), Value:toFloat(line.Value)}]->(block)
        // CREATE (block)-[:Creates  {Height:toInteger(line.Height), Value:toFloat(line.Value)}]->(target)
        //
        // WITH line, source, target, block
        //
        // CALL apoc.create.relationship(
        //     source,
        //     line.EdgeType,
        //     {
        //         Height:toInteger(line.Height),
        //         Value:toFloat(line.Value)
        //     },
        //     target)
        // YIELD rel
        // RETURN distinct 'DONE'
        //

        string l = Property.lineVarName, s = "source", t = "target", b = "block";

        /*
        var builder = new StringBuilder(
            $"LOAD CSV WITH HEADERS FROM '{csvFilename}' AS {l} " +
            $"FIELDTERMINATOR '{Neo4jDbLegacy.csvDelimiter}' ");
        
        builder.Append(
            $"MATCH " +
            $"({s}:{TxNodeStrategy.Label} {{{Props.T2TEdgeSourceTxid.GetSetter()}}}), " +
            $"({t}:{TxNodeStrategy.Label} {{{Props.T2TEdgeTargetTxid.GetSetter()}}}), " +
            $"({b}:{BlockNodeStrategy.Label} {{{Props.Height.GetSetter()}}}) ");

        builder.Append(
            GetRedeemsEdgeQuery(b, s) + " " +
            GetCreatesEdgeQuery(b, t) + " ");

        builder.Append(
            $"WITH {l}, {s}, {t}, {b} ");

        builder.Append(
            GetApocCreateEdgeQuery(GetEdgePropertiesBase(), s, t));

        builder.Append(
            $" RETURN distinct 'DONE'");
        

        return builder.ToString();
        */
        return string.Empty;
    }
}