using EBA.Utilities;

namespace EBA.Graph.Db.Neo4jDb.Bitcoin.Strategies;

public class S2SEdgeStrategy(bool serializeCompressed) : BitcoinEdgeStrategy(serializeCompressed)
{
    public override string GetCsvHeader()
    {
        return string.Join(
            csvDelimiter,
            [
                $":START_ID({ScriptNodeStrategy.Label})",
                $":END_ID({ScriptNodeStrategy.Label})",
                Props.EdgeValue.TypeAnnotatedCsvHeader,
                Props.Height.TypeAnnotatedCsvHeader,
                ":TYPE"
            ]);
    }

    public override string GetCsv(IGraphComponent edge)
    {
        return GetCsv((S2SEdge)edge);
    }

    public static string GetCsv(S2SEdge edge)
    {
        /// Note that the ordre of the items in this array should 
        /// match header.
        return string.Join(
            csvDelimiter,
            [
                edge.Source.Address,
                edge.Target.Address,
                Helpers.Satoshi2BTC(edge.Value).ToString(),
                edge.BlockHeight.ToString(),
                edge.Type.ToString()
            ]);
    }

    public override string GetQuery(string csvFilename)
    {
        // The following is an example of a query generated by this method.
        // Indentation is added for better readability and is not included
        // in the generated query.
        //
        // 
        // LOAD CSV WITH HEADERS FROM 'file:///filename.csv' AS line
        // FIELDTERMINATOR '	'
        //
        // MATCH
        //     (source:Script {Address:line.SourceAddress}),
        //     (target:Script {Address:line.TargetAddress}),
        //     (block:Block {Height:toInteger(line.Height)})
        //
        // CREATE (source)-[:Redeems {Height:toInteger(line.Height), Value:toFloat(line.Value)}]->(block)
        // CREATE (block)-[:Creates  {Height:toInteger(line.Height), Value:toFloat(line.Value)}]->(target)
        //
        // WITH line, block, source, target
        //
        // CALL apoc.create.relationship(
        //     source,
        //     line.EdgeType,
        //     {
        //         Height:toInteger(line.Height),
        //         Value:toFloat(line.Value)
        //     },
        //     target)
        // YIELD rel
        // RETURN distinct 'DONE'
        //

        string l = Property.lineVarName, b = "block", s = "source", t = "target";

        var builder = new StringBuilder(
            $"LOAD CSV WITH HEADERS FROM '{csvFilename}' AS {l} " +
            $"FIELDTERMINATOR '{Neo4jDbLegacy.csvDelimiter}' ");

        builder.Append(
            $"MATCH " +
            $"({s}:{ScriptNodeStrategy.Label} {{{Props.EdgeSourceAddress.GetSetter()}}}), " +
            $"({t}:{ScriptNodeStrategy.Label} {{{Props.EdgeTargetAddress.GetSetter()}}}), " +
            $"({b}:{BlockNodeStrategy.Label} {{{Props.Height.GetSetter()}}}) ");

        builder.Append(GetRedeemsEdgeQuery(b, s) + " ");
        builder.Append(GetCreatesEdgeQuery(b, t) + " ");

        builder.Append($"WITH {l}, {b}, {s}, {t} ");

        builder.Append(GetApocCreateEdgeQuery(GetEdgePropertiesBase(), s, t));

        builder.Append(" RETURN distinct 'DONE'");

        return builder.ToString();
    }
}