using EBA.Utilities;

namespace EBA.Graph.Db.Neo4jDb.Bitcoin.Strategies;

public class T2TEdgeStrategy(bool serializeCompressed) : BitcoinEdgeStrategy(serializeCompressed)
{
    public override string GetCsvHeader()
    {
        return string.Join(
            csvDelimiter,
            [
                $":START_ID({TxNodeStrategy.Label})",
                $":END_ID({TxNodeStrategy.Label})",
                Props.EdgeValue.TypeAnnotatedCsvHeader,
                Props.Height.TypeAnnotatedCsvHeader,
                ":TYPE"
            ]);
    }

    public override string GetCsv(IGraphComponent edge)
    {
        return GetCsv((T2TEdge)edge);
    }

    public static string GetCsv(T2TEdge edge)
    {
        return string.Join(
            csvDelimiter,
            [
                edge.Source.Txid,
                edge.Target.Txid,
                Helpers.Satoshi2BTC(edge.Value).ToString(),
                edge.BlockHeight.ToString(),
                edge.Type.ToString()
            ]);
    }

    public override string GetQuery(string csvFilename)
    {
        // The following is an example of the query generated by this method.
        // Indentation and line break is added for readability and is not 
        // included in the generated query.
        //
        //
        // LOAD CSV WITH HEADERS FROM 'file:///filename.csv' AS line
        // FIELDTERMINATOR '	'
        //
        // MATCH
        //     (source:Tx {Txid:line.SourceId}),
        //     (target:Tx {Txid:line.TargetId}),
        //     (block:Block {Height:toInteger(line.Height)})
        //
        // CREATE (source)-[:Redeems {Height:toInteger(line.Height), Value:toFloat(line.Value)}]->(block)
        // CREATE (block)-[:Creates  {Height:toInteger(line.Height), Value:toFloat(line.Value)}]->(target)
        //
        // WITH line, source, target, block
        //
        // CALL apoc.create.relationship(
        //     source,
        //     line.EdgeType,
        //     {
        //         Height:toInteger(line.Height),
        //         Value:toFloat(line.Value)
        //     },
        //     target)
        // YIELD rel
        // RETURN distinct 'DONE'
        //

        string l = Property.lineVarName, s = "source", t = "target", b = "block";

        var builder = new StringBuilder(
            $"LOAD CSV WITH HEADERS FROM '{csvFilename}' AS {l} " +
            $"FIELDTERMINATOR '{Neo4jDbLegacy.csvDelimiter}' ");

        builder.Append(
            $"MATCH " +
            $"({s}:{TxNodeStrategy.Label} {{{Props.T2TEdgeSourceTxid.GetSetter()}}}), " +
            $"({t}:{TxNodeStrategy.Label} {{{Props.T2TEdgeTargetTxid.GetSetter()}}}), " +
            $"({b}:{BlockNodeStrategy.Label} {{{Props.Height.GetSetter()}}}) ");

        builder.Append(
            GetRedeemsEdgeQuery(b, s) + " " +
            GetCreatesEdgeQuery(b, t) + " ");

        builder.Append(
            $"WITH {l}, {s}, {t}, {b} ");

        builder.Append(
            GetApocCreateEdgeQuery(GetEdgePropertiesBase(), s, t));

        builder.Append(
            $" RETURN distinct 'DONE'");

        return builder.ToString();
    }
}