using AAB.EBA.Blockchains.Bitcoin.ChainModel;
using AAB.EBA.TestDataGenerator;
using Moq;
using Moq.Protected;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace AAB.EBA.Tests;

/// Since it takes a decent amount of time to Mock the client
/// for all the endpoints, using ClientFixture helps run the 
/// initialization/mocking once, and reuse the mocked client 
/// in different tests. However, since XUnit does not currently
/// support parametrized fixture (https://github.com/xunit/xunit/issues/352),
/// this fixture mocks client for every endpoint that tests
/// assert. For instance, if one test class implements assertions 
/// on the block with height 10 and another test class on the 
/// block with height 100, both tests will receive a client 
/// that is mocked to respond for both blocks 10 and 100.

public class ClientFixture
{
    public HttpClient Client { get; }

    public List<long> MockBlocks { get; }

    public static string MockDataDir
    {
        get { return Path.Combine(AppContext.BaseDirectory, Dirs.MockData); }
    }    
    public static string BitcoinCoreResourcesDir
    {
        get { return Path.Combine(MockDataDir, Dirs.Bitcoin, Dirs.BitcoinCoreResponses); }
    }
    public static string BitcoinExpectedOutputsDir
    {
        get { return Path.Combine(MockDataDir, Dirs.Bitcoin, Dirs.ExpectedOutputs); }
    }

    public ClientFixture()
    {
        MockBlocks =
        [
            // 100,
            // 3000,
            // 30000,
            71036
            // 120460, 120461, 120462, 120463,
            // 199233,
            // 300000,
            // 700000,
            // 714460
        ];

        var parameters = new List<MessageHandlerMockingParams>
        {
            new(endpoint: "chaininfo.json",
                response: File.ReadAllText(Path.Combine(BitcoinCoreResourcesDir, Files.ChainInfo)))
        };

        parameters.AddRange(GetBlockMockingParams(MockBlocks));

        /// For every endpoint that BitcoinChainAgent accesses on bitcoin-qt, 
        /// this mocking approach creates the endpoint and populates it 
        /// with predefined data (i.e., Resources/APIMock/**). For instance,
        /// BitcoinChainAgent will GET the `/rest/chaininfo.json` endpoint to
        /// determine if the client is on the `main` chain or not. For
        /// this to work, this mocking approach loads a predefined 
        /// response (stored as `/Resources/APIMock/chaininfo.json`)
        /// and sets as the `/rest/chaininfo.json` response. Hence,
        /// enabling the simulating API calls to bitcoin-qt.
        /// All the data under the `Resources` directory are
        /// generated by `AAB.EBA.TestDataGenerator`.
        var mock = GetMockMessageHandler(parameters);

        Client = new HttpClient(mock.Object)
        {
            BaseAddress = new Uri("http://localhost:8332/")
        };
    }

    private static List<MessageHandlerMockingParams> GetBlockMockingParams(List<long> blocksToMock)
    {
        var prms = new List<MessageHandlerMockingParams>();

        var blockFiles = Files.GetAllMockBlockFilenames(BitcoinCoreResourcesDir);
        foreach (var blockFile in blockFiles)
        {
            Block? block2;
            using (var stream = new StreamReader(blockFile))
                block2 = JsonSerializer.Deserialize<Block>(stream.BaseStream);
            block2 = block2 ?? throw new Exception($"Invalid JSON file {blockFile}");

            if (!blocksToMock.Contains(block2.Height))
                continue;

            prms.Add(new MessageHandlerMockingParams(
                $"blockhashbyheight/{block2.Height}.hex", block2.Hash));

            prms.Add(new MessageHandlerMockingParams(
                $"block/{block2.Hash}.json", File.ReadAllText(blockFile)));

            foreach (var tx in block2.Transactions)
                foreach (var input in tx.Inputs.Where(x => !string.IsNullOrEmpty(x.Txid)))
                {
                    var txFile = Path.Combine(
                        BitcoinCoreResourcesDir,
                        Files.GetMockTxFilename(input.Txid));
                    if (File.Exists(txFile))
                        prms.Add(new MessageHandlerMockingParams(
                            $"tx/{input.Txid}.json",
                            File.ReadAllText(txFile)));
                }
        }

        return prms;
    }

    private static Mock<HttpMessageHandler> GetMockMessageHandler(
        List<MessageHandlerMockingParams> parameters)
    {
        /// This approach of mocking HttpClient is partially based 
        /// on the following StackOverflow topic:
        /// https://stackoverflow.com/a/44028625/947889
        ///
        /// Note that it is essential to create a new instance
        /// of HttpResponseMessage at the ReturnsAsync func body.
        /// Accordingly, everytime a call is made to an endpoint, 
        /// a new response is returned to the caller. Otherwise
        /// (reusing an existing HttpResponseMessage, e.g., by 
        /// creating it outside the func), will return the same 
        /// response to the second caller on a given endpoint. 
        /// The second caller will start reading the response 
        /// from the point the first caller had left; if left 
        /// at the end, then the second caller will read an 
        /// empty string.

        var mock = new Mock<HttpMessageHandler>();

        Parallel.ForEach(parameters, (param) =>
        {
            mock
            .Protected()
            .Setup<Task<HttpResponseMessage>>(
                "SendAsync",
                ItExpr.Is<HttpRequestMessage>(
                    x => x.RequestUri!.AbsolutePath.Contains(param.Endpoint)),
                ItExpr.IsAny<CancellationToken>())
            .ReturnsAsync(() => new HttpResponseMessage()
            {
                Content = param.Response
            });
        });

        return mock;
    }
}
